// Generated by script/generate-decoder-manifest.mjs. Do not edit.
public enum DecoderManifest {
    public static let sdkVersion = "1.0.0"
    public static let abiVersion = "1.0"
    public static let decodableFormatIDs: Set<String> = ["xm", "mod", "it", "s3m", "mo3", "mtm", "fc13", "fc14", "nsf", "spc", "sid", "sc68", "ym", "sap", "ahx", "thx", "mid", "v2m", "bp", "rad", "d00", "hsc", "amd"]
}
